### PR TITLE
Data Integration

### PR DESCRIPTION
**Pull request by sgratzl**
first version of #337 

image

image

image

image

### CODE REVIEW

**Comment by jeffbaumes** [comment]
Maybe my environment is set up incorrectly, but when I attempt to integrate two CSV files (really the same CSV file data_original.csv uploaded two times), I get the following when performing the integration:

```
AssertionError: Invalid csv_file provided
Traceback (most recent call last):
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jeff/.virtualenvs/viime-RvDICfqH/lib/python3.7/site-packages/webargs/core.py", line 448, in wrapper
    return func(*args, **kwargs)
  File "/Users/jeff/code/viime/viime/views.py", line 191, in merge_csv_files
    validated_table = ValidatedMetaboliteTable.create_from_csv_file(csv_file)
  File "/Users/jeff/code/viime/viime/models.py", line 714, in create_from_csv_file
    assert table is not None, 'Invalid csv_file provided'
AssertionError: Invalid csv_file provided
```

It happens when I click Create with this dialog:
image

**Comment by jeffbaumes** [comment]
Yep that fixed it.

So far I can't find anything else incorrect about the functionality. The "remerge" button is nice and seems to work properly. The number indicator when selecting tables to merge is really nice as a way to know what order the tables will be merged.

Would be nice if when you clicked on a source table in a merged table's details page it navigated you to that table.

The Data Source row in the merged table is great provenance information and could be used in visualizations to distinguish columns, but since it is a database ID it is not user-friendly to look at. I can't yet think of a better clean solution that doesn't require a lot of UI and bookkeeping. You could let the user give a name to each dataset which is used in the Data Source row. This name would need to be set when initially running merge and would need to be available in the table details page so the user could track provenance based on the custom name. We could alternately just use the data source name, but that is not guaranteed to be unique, and if the source data name is changed later, the Data Source row will be out of sync.

Just thought of this idea that might work: could the Data Source row just contain a 1-based number which matches the number beside the dataset checkbox when merge is initially run (the table ordering)? The user would then be able to just look down the list in the details page (which could be numbered for clarity) to see which dataset is which.

**Comment by sgratzl** [comment]
done

**Comment by jeffbaumes** [comment]
Something a bit strange is going on with the details page. The light gray background stops before the groups, and scrolling does not keep the header or sidebar fixed like I'd expect.

image

**Comment by jeffbaumes** [comment]
Though I could not give the front end a thorough review, it works as expected, I did not see anything too strange in the front end code, and @subdavis is super busy, so this is good to merge without further review.

**Pull request merged**
