### PR TITLE
Mask image for banner

### PR DESCRIPTION
**Pull request by jtomeck**
Here is the SVG of the image to do the masking for.

### CODE REVIEW

**Comment by sgratzl** [comment]
new version using dummy image (original is already masked)

image

**Comment by jtomeck** [comment]
I just tried swapping the image, but could not get it working. In the interest of time, I'll just post the images here and defer to your implementation @sgratzl if that's ok.

viime_screen_lg
Large version

viime_screen_sm
Small version

**Comment by sgratzl** [comment]
done (even with nice srcset for optimized image loading)

image

**Comment by jeffbaumes** [comment]
In the mobile layout, it seems the image stretches. Here it is around 850px wide:

image

**Pull request merged**
