### PR TITLE
Remove custom classes from pretreatment menu

### PR DESCRIPTION
**Pull request by subdavis**
Remove a ton of hacky CSS that will have to be gutted before a vuetify upgrade anyway.

This PR damages UX in favor of maintainability.

Notice how sub-lists aren't nicely indented anymore (like Impute Table).

Screenshot from 2020-06-09 15-02-01

### CODE REVIEW

**Comment by jeffbaumes** [comment]
See #542 for suggested changes.

> That's a vuetify design choice, and I agree with the default behavior. The direction of the arrow tells you what will happen when the arrow is clicked.

Agree. I just had the mental memory of how it worked before and saw it as a bug, but I now see it as a feature to change the arrow directions to normalize to the MD spec.

**Comment by mvandenburgh** [comment]
My issue was addressed and the UI looks better now, looks good to me.

**Comment by subdavis** [comment]
> Any way to get rid of the small space on top of the list?

Done

> hover

I couldn't find a way to do this.  `inactive` prop gives the styling we want, but it also disables click and router-link behaviors.  Because the list group adds the right drop-down icon, I can't even adjust the width to make the left side fit into the hovered background.

**Comment by jeffbaumes** [comment]
> > hover
> 
> I couldn't find a way to do this. `inactive` prop gives the styling we want, but it also disables click and router-link behaviors. Because the list group adds the right drop-down icon, I can't even adjust the width to make the left side fit into the hovered background.

I'm sure you've spent all the time I'd want spent on this for now. Please create an issue for the backlog that we may or may not get to. Thanks for looking into it.

**Pull request merged**
