### PR TITLE
clustered heatmap

### LINKED ISSUE #267: create clustered heatmap

### PR DESCRIPTION
**Pull request by sgratzl**
closes #267 

based on #265 (validated data in store) and #255 (vue-resize)

first version of a hierarchical clustered heatmap of the validated measurements. 

image

From an interaction point of view, so far only highlighting of rows/columns. Collapsing a level requires some kind of aggregation (median?, mean?)

### CODE REVIEW

**Comment by jeffbaumes** [comment]
I think mean would be fine for aggregation.

**Comment by waxlamp** [comment]
Is it possible to use a more ["standard"](https://en.wikipedia.org/wiki/Dendrogram#/media/File:Heatmap_RNAseqV2_1.png) dendrogram? Or do we like the wavier style?

**Comment by jeffbaumes** [comment]
I'd think it would be an easy change (or can be made an option). We can ask Tom which he prefers.

**Comment by sgratzl** [comment]
image

image

**Comment by sgratzl** [comment]
image

**Comment by subdavis** [comment]
pending @jbeezley  I think?

**Pull request merged**
