### PR TITLE
Download Table

### PR DESCRIPTION
**Pull request by sgratzl**
based on #343 

Adds another point to the main bar: `Download Data`. Allowing the user to download the validated table, a filtered version of it, a list of metabolites, or a list of samples in CSV format

image

### CODE REVIEW

**Comment by jeffbaumes** [comment]
@sgratzl can we include group and metadata rows/columns to the downloaded table?

**Comment by sgratzl** [comment]
> @sgratzl can we include group and metadata rows/columns to the downloaded table?

done

**Comment by sgratzl** [comment]
image

will become

image

**Comment by sgratzl** [comment]
> Looks like the group column is still missing.

the group is already encoded in the row column by color and the group label is seen in the sample filter? should I duplicate it, if yes, still the row color coding?

**Pull request merged**
